### ISSUE TITLE
Failed to open stream: livecall.js

### ISSUE THREAD

**Issue by vemi2709** [r4phf43l/livecall#1]
When GLPI is installed in subdirectory I get an error when saving the script:
glpiphplog.WARNING:   *** PHP Warning (2): file_put_contents(/var/www/html/plugins/livecall/livecall.js): Failed to open stream: No such file or directory in /var/www/html/glpi/plugins/livecall/setup.php at line 84
glpiphplog.WARNING:   *** PHP Warning (2): file_put_contents(/var/www/html/plugins/livecall/livecall.js): Failed to open stream: No such file or directory in /var/www/html/glpi/plugins/livecall/front/index.form.php at line 59

I fixed this by changing files setup.php and front/index.form.php to read:
$path = GLPI_ROOT . '/' . Plugin::getWebDir('livecall', false) . '/';

**Comment by r4phf43l** [comment]
Thanks, fixed.
