### ISSUE TITLE
The chat window launches

### ISSUE THREAD

**Issue by Smiley-k** [r4phf43l/livecall#2]
HI

I configured livechat in Rocket.Chat placed the code, but the chat window is not active and there is no way to run.

![image](https://user-images.githubusercontent.com/11009787/218305847-3b8b8f9b-0e58-4a38-8c80-d31009a7f469.png)

**Comment by r4phf43l** [comment]
Hey! It seems to be a problem with your Rocket.Chat server. Can you post, from your browser's developer tools, the console error messages and network errors?

**Comment by Smiley-k** [comment]
Yes there is an error, but I can not figure out how to solve it, in the reverse proxy I added the parameter  
**_add_header X-Frame-Options SAMEORIGIN;_**

Loading "https://in.domain.com/livechat" in a frame is forbidden by the "X-Frame-Options" directive set in "sameorigin".


![image](https://user-images.githubusercontent.com/11009787/218376870-6748065a-6a6a-4c82-8979-6119a5c16343.png)


and

Uncaught ReferenceError: livechat is not defined
    at Object.<anonymous> (livecall.js?v=3ed4563e6f8360e1e8ac07a4202aa72a5c834cbd:1:444)
    at widget.js:502:4
    at Array.forEach (<anonymous>)
    at Module.<anonymous> (widget.js:501:7)
    at n (bootstrap:19:22)
    at bootstrap:83:10
    at rocketchat-livechat.min.js:1:920

**Comment by r4phf43l** [comment]
@Smiley-k about "X-Frame-Options": you should adjust your server (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options).

About "Uncaught ReferenceError: livechat is not defined" can you post your script config?

**Comment by Smiley-k** [comment]
Dear @r4phf43l  could you please tell me where I should and what parameter to use (I'm confused) I see a lot of similar problems with RC on the Internet on this subject  

my script config

```

	(function(w, d, s, u) {
		w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
		var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
		j.async = true; j.src = 'https://chat.domain.com/livechat/rocketchat-livechat.min.js';
		h.parentNode.insertBefore(j, h);
	})(window, document, 'script', 'https://chat.domain.com/livechat');

RocketChat( function() {
    this.registerGuest( {
        name: livechat('name'),
    } );
} );
 
```
