### ISSUE TITLE
Username not transferring from glpi to rocketchat

### ISSUE THREAD

**Issue by r0bertk** [r4phf43l/livecall#3]
Hello, I am using the function:
RocketChat( function() {
    this.registerGuest( {
        name: livechat('name'),
    } );
} );
but the data is not transferred to Rocketchat. The user from glpi in Rocketchat appears as a guest-1.
I understand that the username should be posted by GLPI?

**Comment by r4phf43l** [comment]
I will do some tests, there are some message error in the DevTools Console?

**Comment by r0bertk** [comment]
Tkank you but it's already working for me. The problem was that in the instruction there is a call via name: livechat('name') and it should be : name: **livecall**('name')

Working form:
RocketChat( function() {
this.registerGuest( {
name: livecall('name')
} );
} );
